development:
  adapter: postgresql
  encoding: utf8
  database: kupon_dev
  username: kupon_user
  password: 
  host: localhost
test:
  adapter: postgresql
  encoding: utf8
  database: kupon_test
  username: kupon_user
  password: 
  host: localhost