# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 395ff40d25c743f9f378783392be19c0ece6c240f1ed49e8bc6db03ffd17eee3d32f52257d109d72bebc1ae0e6dbf7338c9f879dcf8943ed7ef5f248cb29838f

test:
  secret_key_base: a4ef0f0f5b6abff6ae395a09b66585591a930a6fae75ed9ec8072e8f1017d1301beaa8f74d695edb104648ef264f9a4c825dd3e2cf52190dc84a38db9c5fb817

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
